# Site settings
title: Madeline Hanitijo
email: madeline.hanitijo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Illustrator, game dev, unwitting software dev
baseurl:  # the subpath of your site, e.g. /blog/
url: "https//ymorts.github.io"
twitter_username: _stormwhy
github_username:  "ymorts"

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  illust:
    output: true
    permalink: /illust/:path/
    sort_by: order
  games:
    output: true 
    permalink: /games/:path/
